spring:
  application:
    name: hexagonal-arch-example
    version: 1.0.0
  datasource:
    url: jdbc:h2:mem:footballdb
    username: sa
    password: football
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect